version: "3.7"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/:/code/
    ports:
      - 8000:$APP_PORT
    command: ./entrypoint.sh
    environment:
      APP_PORT: 8000
    env_file:
      - .env
