name: validate

on:
    workflow_dispatch:
    pull_request:
      branches: [ main ]
    push:
      branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: read python_version
        id: python_version
        uses: juliangruber/read-file-action@v1
        with:
          path: .python-version

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ steps.terraform_version.outputs.content }}

      - uses: pre-commit/action@v2.0.0
        with:
          extra_args: --all-files
